### ISSUE TITLE
Translator broken on arXiv and GitHub after upgrading to 5.0

### ISSUE THREAD

**Issue by louy2** [zotero/translators#1369]
I have not tested others but these two affect my workflow mostly. 

GitHub

```
[JavaScript Error: "JSON.parse: unexpected end of data at line 1 column 1 of the JSON data" {file: "jar:file:///C:/Users/667/AppData/Roaming/Mozilla/Firefox/Profiles/4epd07yj.default/extensions/zotero@chnm.gmu.edu.xpi!/inject/translate_inject.js line 63 > eval" line: 99}]
```

```
Firefox can’t establish a connection to the server at wss://live.github.com/_sockets/VjI6MTc4MDY3MTIwOmNiZmQzNzNhNjg3MjJiMTE1ZWI1ZmU5ODYxMzUzMjcwZjUxMjhjYjM1M2I5M2FiNGQ5ZDAyMmU0ZmU0NTgzYWE=--147e6ada12e44af5d75ce6826f7bcae130e2ec8d.  github-13fa3aa50ac8f9fa9a7d198f0cd13b0905775d39446ad076d17d8f74a998438a.js:5:31728
The connection to wss://live.github.com/_sockets/VjI6MTc4MDY3MTIwOmNiZmQzNzNhNjg3MjJiMTE1ZWI1ZmU5ODYxMzUzMjcwZjUxMjhjYjM1M2I5M2FiNGQ5ZDAyMmU0ZmU0NTgzYWE=--147e6ada12e44af5d75ce6826f7bcae130e2ec8d was interrupted while the page was loading.  github-13fa3aa50ac8f9fa9a7d198f0cd13b0905775d39446ad076d17d8f74a998438a.js:5:31728
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data at jar:file:///C:/Users/667/AppData/Roaming/Mozilla/Firefox/Profiles/4epd07yj.default/extensions/zotero@chnm.gmu.edu.xpi!/inject/translate_inject.js line 63 > eval:99  zotero.js:185:4
```

arXiv

```
[JavaScript Error: "invalid 'in' operand elements" {file: "jar:file:///C:/Users/667/AppData/Roaming/Mozilla/Firefox/Profiles/4epd07yj.default/extensions/zotero@chnm.gmu.edu.xpi!/zotero/utilities.js" line: 1244}]
```

```
XML Parsing Error: no root element found
Location: https://arxiv.org/abs/1707.03491
Line Number 1, Column 1:  1707.03491:1:1
TypeError: invalid 'in' operand elements at jar:file:///C:/Users/667/AppData/Roaming/Mozilla/Firefox/Profiles/4epd07yj.default/extensions/zotero@chnm.gmu.edu.xpi!/zotero/utilities.js:1244 zotero.js:185:4
```

In the meantime these errors are repeating in `background.js`:

```
[JavaScript Error: "Script injection timed out" {file: "moz-extension://6418ac8d-d1eb-4d69-8b60-3ccf294a6332/background.js" line: 260}]

[JavaScript Error: "tab is undefined" {file: "moz-extension://6418ac8d-d1eb-4d69-8b60-3ccf294a6332/background.js" line: 594}]

[JavaScript Error: "getTranslators: detection is already running" {file: "jar:file:///C:/Users/667/AppData/Roaming/Mozilla/Firefox/Profiles/4epd07yj.default/extensions/zotero@chnm.gmu.edu.xpi!/zotero/translation/translate.js" line: 1136}]
```

**Comment by adam3smith** [comment]
Works for me, so this isn't a translator issue and likely not a general Zotero issue. If you're still having this issue, please report through forums.zotero.org.

**Comment by zachjweiner** [comment]
For what it's worth, I'm having the same issue on Chrome and Windows 10.

**Comment by adam3smith** [comment]
> If you're still having this issue, please report through forums.zotero.org.

We use issues here as a bug tracker of confirmed bugs; we do all bug triage on the forums, so please do follow up there with issues. That said, looking at this error again, I'm pretty sure this is just the consequence of the arXiv API being down (the error occurs when Zotero tries to parse an emptry string as XML). In my experience, the API is not super stable, so that happens occasionally and there's not much we can do about it.

**Comment by zachjweiner** [comment]
It would appear you are correct, @adam3smith -- it's working for me again. Glad to know it's on arXiv's end.
