### ISSUE TITLE
lint fails in travis in a forked repo and non-master branch name

### ISSUE THREAD

**Issue by i3v** [zotero/translators#1967]
The `lint` fails for me in Travis, when I push to a non-master branch (a forked repo, created to to test before PR): 

```
$ git diff -z --name-only $TRAVIS_COMMIT_RANGE *.js | xargs -0 npm run lint --
> translators-check@1.0.2 lint /home/travis/build/i3v/translators
> teslint "eLibrary.ru.js"
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
child_process.js:650
    throw err;
    ^
Error: Command failed: git diff --name-status master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
    at checkExecSyncError (child_process.js:607:13)
    at Object.execSync (child_process.js:647:13)
    at exec (/home/travis/build/i3v/translators/.ci/eslint-plugin-zotero-translator/lib/translators.js:158:22)
    at new Cache (/home/travis/build/i3v/translators/.ci/eslint-plugin-zotero-translator/lib/translators.js:182:23)
    at Object.<anonymous> (/home/travis/build/i3v/translators/.ci/eslint-plugin-zotero-translator/lib/translators.js:240:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! translators-check@1.0.2 lint: `teslint "eLibrary.ru.js"`
npm ERR! Exit status 1

```
(Note that `git diff -z --name-only $TRAVIS_COMMIT_RANGE *.js` works OK by itself.)

It looks like [this code](https://github.com/zotero/translators/blob/07bc803ad69e1ea43a3b7fff94b1e1d0f3f0a708/.ci/eslint-plugin-zotero-translator/lib/translators.js#L182) expects that `master` branch is available. But Travis only fetches the non-master branch I've pushed to.

One way to fix this is to add [a couple of commands](https://stackoverflow.com/a/19644027/1032586) to make sure all branches are downloaded:
```
- git checkout --detach
- git fetch origin '+refs/heads/*:refs/heads/*'
```
.  This causes 0.7 sec overhead (when it actually creates the `master` branch).

So... Maybe, as a quick fix, it would be acceptable to add these commands to `.travis.yml`?

**Comment by zuphilip** [comment]
You can run the linting locally on your PC and then also use directly fix most of the issues automatically. For that you need to install it first:
```
npm ci
```
and can then run the linting of one translator by
```
npm run lint -- ACS\ Publications.js
```
resp. including to fix the issues
```
npm run lint -- ACS\ Publications.js --fix
```
(Configuring Travsi for forked repositories might be out of scope for us.)

**Comment by i3v** [comment]
> You can run the linting locally on your PC

Sure...

> Configuring Travsi for forked repositories might be out of scope for us

I understand that this is hardly a high-priority feature either way. I just hoped that adding this tiny fix (so that everything would just automatically work in a forked repo) won't be a problem and that this might save some time for those who might run into this. 
If you don't consider this fix nice enough... Well.. I agree there' no real major problem here.
