### ISSUE TITLE
YouTube titles not being read, causing YouTube translator to be skipped

### ISSUE THREAD

**Issue by geofferb** [zotero/translators#3290]
When parsing a YouTube URL, the server attempts to use the YouTube translator, but ultimately skips it because it fails to read the title with the below error:
```
(1)(+0000000): Translation using YouTube failed

(1)(+0000000): Error: No title specified for item

    Error: No title specified for item
        at Object._itemDone (C:\zotero\modules\translate\src\translation\translate.js:615:32)
        at Object._itemDone (C:\zotero\src\translation\sandboxManager.js:96:17)
        at Object.complete (C:\zotero\modules\translate\src\translation\translate.js:1965:26)
        at scrape (eval at <anonymous> (C:\zotero\src\translation\sandboxManager.js:70:4), <anonymous>:148:7)
        at doWeb (eval at <anonymous> (C:\zotero\src\translation\sandboxManager.js:70:4), <anonymous>:75:3)
        at Zotero.Translate.Web.rest (C:\zotero\modules\translate\src\translation\translate.js:1346:49)
        at C:\zotero\modules\translate\src\translation\translate.js:1331:39
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
  ```
These lines in the translator are responsible for parsing the title:
https://github.com/zotero/translators/blob/7837c4267095812c345c4ea86a3691b10ba07063/YouTube.js#L106C2-L108C59

The titles are read in properly in both in Scaffold and the Zotero desktop client, so this seems to be an issue with the translation server.

**Comment by dstillman** [comment]
The YouTube translator uses scraping for some fields because of this:

https://github.com/zotero/translators/blob/7837c4267095812c345c4ea86a3691b10ba07063/YouTube.js#L101-L103

But when run from translation-server we only have the JSON-LD. So maybe we need to check whether the page is actually built and fall back to JSON-LD for all fields if not.

**Comment by geofferb** [comment]
@dstillman Upon further testing, I've found that the translation-server can only get the useless BreadcrumbList JSON-LD and not the VideoObject one the translator uses. However, it seems to get <meta> tags fine; could those be used as a fallback?

**Comment by dstillman** [comment]
Probably, but we would have to make sure it was only using the meta tags for over-the-wire saves and never using them for Connector-based saves, due to the problem explained in the comment. So we'd have to make sure we were detecting that properly.

> Also, is there a way to see the HTML retrieved by translation-server?

Yes, you can add `Zotero.debug(doc.documentElement.innerHTML)` or similar. (But it's likely just the same as you'd get with curl.)
